### ISSUE TITLE
Borderless window placement offset issue.

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Chobby#52] opened 2016-11-29 21:37 UTC
* borderless window appears partially offscreen with some of screen space unused:.

 * if you switch chobby to windowed, it locks mouse into the window, there is no way to even maximize the window and you play in small 800x400 window. 
Locking mouse in windowed mode is SUPER bad do not ever do it. It can make people force reboot their pc, because there is no mouse-based solution and not all know keyboard shortcuts like alt+f4

 * when game ends and lobby auto swithces to windowed mode, it appears as small window again, instead of remembering old window size

 * borderless window makes second screen unusable - you cannot move your mouse out.

**Comment by GoogleFrog** [comment] 2016-11-30 16:22
Is 1) recent? Try /fullscreen /fullscreen to see if that fixes it. Then add the toggles into the code and see if that fixes it.

3) just needs some settings saving written.

2) and 4) are ZK. This is a common, default-on, option for games such as fast-paced RTS. Alt+Tab should be known by everyone. Does the full mouse locking of FPS and similar cause people to restart their computer?

**Comment by Licho1** [comment] 2016-11-30 19:49
1) yes its recent - havent had this bug for month or so

4) not if they can otherwise close the window. However if buttons to do so are offscreen and button on window inaccessible its pretty hard to solve.. 

Regarding other RTS, we should check how they do it, I think that lock is on in fullscreen but off in windowed/borderless.

**Comment by GoogleFrog** [comment] 2016-12-03 02:13
Needless to say, I can't reproduce 1). Sometimes I change things in the screen size setting part of the widget and it breaks for some people and works for others.

**Comment by GoogleFrog** [comment] 2016-12-08 05:07
Try aggressively setting borderless window through the settings.

**Comment by Licho1** [comment] 2016-12-14 21:40
Tested with zkmenu:test 
There is no aggtressivity settings and window position is not remembered.

Repro steps:
1) configure chobby to be windowed in lobby and borderless ingame
2) maximize window
3) start game
4) exit game

-> window appears not maximized and in different position.
Note that window position and size is not enough to describe it, window state is a separate value.

**Comment by GoogleFrog** [comment] 2016-12-16 11:29
zk:test is not where development changes are visible. Dev is in the chobby repo.

**Comment by Licho1** [comment] 2016-12-16 12:47
Its not on rapid?

**Comment by GoogleFrog** [comment] 2016-12-16 14:16
It is probably on rapid but idk the tag. chobby:test is likely.

**Comment by Anarchid** [comment] 2017-01-18 13:12
This seems very similar to the `fullscreen fullscreen` issue i would have on Ubuntu where when a game is launched from Chobby, the graphics are offset and cursor click coordinates also don't correspond to visuals.

https://hastebin.com/kemakuvame.lua seems to fix the issue at least for me but @GoogleFrog says it actually causes offset to happen to him.

**Comment by dvr333** [comment] 2017-01-29 06:22
I was able to replicate the borderless issue (or at least a variation, where Chobby on a second monitor in a window causes Zero-K in borderless mode to only take up as much screen space as the second monitor) several times. Log is attached.

Aggressively setting borderless fixes this problem.

[20170029061129_infolog.txt](https://github.com/ZeroK-RTS/Chobby/files/737337/20170029061129_infolog.txt)

**Comment by sprunk** [comment] 2018-07-11 16:52
Duplicate of https://github.com/Spring-Chobby/Chobby/issues/354

**Closed by sprunk** 2018-07-11 16:52 UTC
Labels: help wanted
