### ISSUE TITLE
Copy paste fails when selecting with keyboard

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Chobby#19] opened 2016-10-16 14:23 UTC
Launch chobby, connect to server, open a channel. Type something, press <kbd>Shift</kbd>+<kbd>Home</kbd> or press the left arrow key while holding shift. Try to copy or cut the text. Try to paste and see that it pastes nothing.

But this only happens if you select from right to left, if you select from left to right it works fine! If you make any selection in the input using the mouse it fixes the bug.

**Comment by gajop** [comment] 2017-02-27 15:45
I can't reproduce it anymore. I think it's fixed.
Try to reproduce with newest from https://github.com/Spring-Chobby/Chobby (or wait until it gets merged and released on test)

**Closed by gajop** 2017-02-27 15:45 UTC
Labels: Chili
