### ISSUE TITLE
Chobby consumes 25% for nothing

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Chobby#269] opened 2017-06-26 11:13 UTC
On my notebook(i7 7500u) chobby eats 25% of CPU while I'm idling in lobby(window active)
this makes fans spin, which is not acceptable...

**Comment by GoogleFrog** [comment] 2017-06-27 01:56
Do you have rapid redrawing enabled in the settings?

**Comment by let4be** [comment] 2017-06-27 06:16
Just tried without full speed draw updates (developer section)
Shit blinks everywhere(no game running) and it still consumes above 5% cpu

**Comment by GoogleFrog** [comment] 2017-06-29 14:05
I think you need some level of fullscreen anti aliasing. This is a workaround for flickering.

**Comment by let4be** [comment] 2017-06-29 14:30
and how exactly anti aliasing is supposed to help with flickering? o_O
Is there such an option I can turn on to test somewhere?

**Comment by GoogleFrog** [comment] 2017-06-30 00:45
https://springrts.com/mantis/view.php?id=5625

Change Anti Aliasing to anything through the graphics settings menu.

**Comment by let4be** [comment] 2017-07-09 18:32
just tried - no effect
Settings -> Graphics -> Anti aliasing -> Low
and disabled full speed draw updates + restarted chobby

Everything flickers and jitters, cannot use
Enabled hack back

**Comment by sprunk** [comment] 2018-07-11 17:03
Improved to 22% :P

Duplicate of #465

**Closed by sprunk** 2018-07-11 17:03 UTC
