### ISSUE TITLE
Can't chat after a matchmaker game

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Chobby#498] opened 2018-02-27 22:55 UTC
One cannot chat in either post game window or the main chat window.

How to reproduce: play in the matchmaker and then try to chat.

**Comment by gajop** [comment] 2018-02-27 23:21
essentially duplicate of https://github.com/ZeroK-RTS/Chobby/issues/497

**Comment by GoogleFrog** [comment] 2018-02-28 04:29
Fixed.

**Closed by GoogleFrog** 2018-02-28 04:29 UTC
