### ISSUE TITLE
"match found" notification amplifies all of the game sounds

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Chobby#592] opened 2018-05-15 16:35 UTC
How to reproduce: queue in MM. Wait until someone accepts and get blasted by the amplified game sound.

https://clips.twitch.tv/ToughSquareTaroBrokeBack?tt_medium=create

**Comment by DeinFreund** [comment] 2018-05-15 17:13
Duplicate of #579

**Closed** 2018-05-16 09:12 UTC
