### ISSUE TITLE
tab name completion is case sensitive

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Chobby#253] opened 2017-05-12 00:03 UTC
If you want to tab complete someone's name, you need to be case sensitive. Back in the old zk lobby this wasn't mandatory and very nice a feature.

**Comment by gajop** [comment] 2017-05-24 07:38
Duplicate of https://github.com/ZeroK-RTS/Chobby/issues/47

**Closed by gajop** 2017-05-24 07:38 UTC
Labels: duplicate
