### ISSUE TITLE
Investigate input offset on Anarchid hardware

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#17] opened 2016-10-16 13:11 UTC
Someone needs to get on Anarchids computer and try to codify/investigate the /fullscreen /fullscreen workaround which fixes his input issues.

**Comment by Anarchid** [comment] 2017-02-21 12:05
Duplicate of https://github.com/ZeroK-RTS/Chobby/issues/17

**Comment by Anarchid** [comment] 2017-02-21 12:06
Also https://github.com/ZeroK-RTS/Chobby/issues/52

**Comment by sprunk** [comment] 2018-07-11 16:48
Duplicate of https://github.com/Spring-Chobby/Chobby/issues/354

**Closed by sprunk** 2018-07-11 16:48 UTC
